Run npm run build
> nextn@0.1.0 build
> next build

⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 15.2.3

   Creating an optimized production build ...
 ⚠ Compiled with warnings

./node_modules/@opentelemetry/sdk-node/build/src/TracerProviderWithEnvExporter.js
Module not found: Can't resolve '@opentelemetry/exporter-jaeger' in '/home/runner/work/pdf-bot-web/pdf-bot-web/node_modules/@opentelemetry/sdk-node/build/src'

Import trace for requested module:
./node_modules/@opentelemetry/sdk-node/build/src/TracerProviderWithEnvExporter.js
./node_modules/@opentelemetry/sdk-node/build/src/sdk.js
./node_modules/@opentelemetry/sdk-node/build/src/index.js
./node_modules/@genkit-ai/core/lib/tracing.js
./node_modules/@genkit-ai/ai/lib/evaluator.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/pdf-query.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/pdf-query.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/pdf-query.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/pdf-query.ts

 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
   Collecting page data ...
   Generating static pages (0/7) ...
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Firebase: Error (auth/invalid-api-key).
    at g (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/109.js:4:7290)
    at y (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/109.js:4:7338)
    at o.instanceFactory (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/109.js:4:63039)
    at a.getOrInitializeService (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/109.js:3:102934)
    at a.initialize (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/109.js:3:102303)
    at /home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/109.js:4:61083
    at e9 (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/109.js:4:61112)
    at 92024 (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/977.js:1:10312)
    at t (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/webpack-runtime.js:1:143)
    at 63213 (/home/runner/work/pdf-bot-web/pdf-bot-web/.next/server/chunks/977.js:1:8323)
Export encountered an error on /page: /, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
Error: Process completed with exit code 1.